VAGRANTFILE_API_VERSION = "2"
BOX_IMAGE = "ubuntu/xenial64"

$script = <<-SCRIPT
sudo apt-get install -y net-tools
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = BOX_IMAGE
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", type: "dhcp"
   
  ["org1", "org2"].each do |org|
    config.vm.define("#{org}") do |orgConfig|
      orgConfig.vm.hostname = "#{org}.artchain.com"
      orgConfig.vm.provision "shell", inline: $script
      orgConfig.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
      end
    end
  end
end

