---
- hosts: all
  become: true
  tasks:
  - name: Setup net-tools to support ifconfig command
    apt:
     name: net-tools
     state: present
     update_cache: yes

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  - name: Make docker command sudoless
    file: dest=/var/run/docker.sock owner=vagrant mode=a+x
    notify:
      - docker status

  - name: Install kind
    ansible.builtin.get_url:
      url: https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
      dest: /usr/bin/kind
      mode: a+x

  - name: Install kubectl
    ansible.builtin.get_url:
      url: https://dl.k8s.io/release/v1.22.2/bin/linux/amd64/kubectl
      dest: /usr/bin/kubectl
      mode: a+x

  - name: Check if cluster has been created
    shell: >
      kind get clusters | grep artchain || echo "not be found"
    register: cluster_has_been_created

  - name: Create kubernetes cluster by kind
    shell: >
      kind create cluster --config cluster.yaml
    when: '"artchain" not in cluster_has_been_created.stdout'
    register: createClusterCmd
    tags: createClusterCmd

  - name: Export cluster config
    shell: >
      kind export kubeconfig --name artchain
    register: exportKubeConfigCmd
    tags: exportKubeConfigCmd

  - name: move .kube config and change owner
    shell: >
      sudo mv /root/.kube /home/vagrant/.kube && \
      sudo chown vagrant:docker -R /home/vagrant/.kube
    register: moveKubeConfigCmd
    tags: moveKubeConfigCmd

  handlers:
  - name: docker status
    service: name=docker state=started